services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  init:
    image: pythondavid/baqo:latest
    command: python -m app.commands.start
    env_file:
      - .env
    volumes:
      - ./config/source_verification.yaml:/app/config/source_verification.yaml
      - ./custom_verifications:/app/app/custom_verifications
    depends_on:
      - db

  app:
    image: pythondavid/baqo:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./config/source_verification.yaml:/app/config/source_verification.yaml
      - ./custom_verifications:/app/app/custom_verifications
    depends_on:
      - db
      - redis
      - init

  worker:
    image: pythondavid/baqo:latest
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./config/source_verification.yaml:/app/config/source_verification.yaml
      - ./custom_verifications:/app/app/custom_verifications
    depends_on:
      - db
      - redis
      - init

volumes:
  pgdata:
